name: Terraform Infra Deployment

on:
  push:
    branches:
      # - main
      - none
  pull_request:
    branches:
      - main

jobs:
  Terraform-Planning:
    runs-on: Infra-Runner
    steps:
      - name: Terraform Installer
        uses: autero1/action-terraform@v3

  
